name : cd

on:
  workflow_run:
    workflows: ["ci"]
    types: [completed]
  
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name : pull docker image
      run : sudo docker pull josephremingston/pipeline:latest
    - name : delete the old image
      run : sudo docker rm -f pipeline-container || true
    - name : run docker image
      env:
        DB_URL : ${{secrets.DB_URL}}
      run : sudo docker run -d -p 3000:3000 --name pipeline-container -e DB_URL=DB_$DB_URL josephremingston/pipeline:latest
