name : cd

on:
  worflow_run:
    workflows: ["ci"]
    type:
      - completed
  
jobs:

  build:

    runs-on: self-hosted

    steps:
    - name : pull docker image
      run : sudo docker pull josephremingston/pipleline:latest
    - name : delete the old image
       run : sudo docker rm -f pipeline-container || true
    - name : run docker image
       run : sudo docker run -d -p 3000:3000 --name josephremingston/pipeline-container josephremingston/pipeline
