name: CD Pipeline

on:
  workflow_run:
    workflows: ["Docker Image CI"]
    types:
      - completed

jobs:
  deploy:
    runs-on: self-hosted
    env:
      DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}

    steps:
      - name: Pull Image from Docker Hub
        run: sudo docker pull $DOCKER_USERNAME"/onlyclick-server"

      - name: Delete old container
        run: sudo docker rm -f onlyclick-server-container

      - name: Run Container
        run: sudo docker run -d -p 3000:4433 -e "PORT=4433" --name onlyclick-server-container $DOCKER_USERNAME"/onlyclick-server"